spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/leadestate?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}

# spring.application.name=backend
# spring.datasource.url=jdbc:mysql://leadestate-db.mysql.database.azure.com:3306/leadestate?useSSL=true&requireSSL=true
# spring.datasource.username=admin_leadestate
# spring.datasource.password=Leadestate6767
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# server.port=${PORT:8080}